### ISSUE TITLE
Flexible server installation

### ISSUE THREAD

**Issue by magiraud** [vidjil/vidjil#4]
Some parameters of the server are now hard-coded for our test server [http://rbx.vidjil.org]. This should be more flexible, one should be able to easily install the server on a fresh install.

**Comment by magiraud** [comment]
Specific configurations items have been put in [defs.py.sample](https://github.com/vidjil/vidjil/blob/master/server/web2py/applications/vidjil/modules/defs.py.sample). We should continue in this way and document all the steps of an installation (rough draft, not up-to-date, in [server.org](https://github.com/vidjil/vidjil/blob/master/doc/server.org)).

**Comment by mikael-s** [comment]
[server.org](https://github.com/vidjil/vidjil/blob/master/doc/server.org) has been greatly improved (*e.g.* ee 230285f4 and 741ce752) and the [docker/vidjil](https://github.com/vidjil/vidjil/blob/master/docker/vidjil) is another good documentation, which provides a flexible installation (tested several times).
