### ISSUE TITLE
French (?) submit button label

### ISSUE THREAD

**Issue by eodus** [vidjil/vidjil#8]
Submit button in data uploading dialog has a little bi misleading title (probably, that means Submit in French)  

See attach
![image](https://user-images.githubusercontent.com/1206380/37622374-86436cc8-2bd2-11e8-9c52-3d974ed53e84.png)

My browser: Chrome for Linux, OS: Ubuntu 14, System locale: US/English

**Comment by magiraud** [comment]
Thank you Alex for reporting. https://gitlab.inria.fr/vidjil/vidjil/issues/3089

**Comment by magiraud** [comment]
It is corrected, it will be deployed on the public server in a few days.
